RESOURCE_GROUP_NAME    = "rg-kubernetes-dev-aue-01"
LOCATION               = "australiaeast"
KUBERNETES_VNET_NAME   = "kubernetes-vnet"
KUBERNETES_SUBNET_NAME = "kubernetes-subnet"
KUBERNETES_NSG_NAME    = "nsg-kubernetes-dev-aue-01"
