name: Deploy Kuberenetes the Hard Way with Terraform
on: ["workflow_dispatch"]

permissions:
      id-token: write
      contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  TF_VAR_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  TF_VAR_VNET_CIDR: "${{ secrets.VNET_CIDR }}"
  STORAGE_ACCOUNT_KEY: "terraform.tfstate.kubernetes_the_hard_ways"
jobs: 
  terraform-init-plan-apply:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./infra/kubernetes_the_hard_way

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -backend-config="resource_group_name=rg-test" -backend-config="storage_account_name=${{ secrets.NAME }}" -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" -backend-config="key=${{ secrets.STORAGE_ACCOUNT_KEY }}"

    - name: Terraform Plan
      run: terraform plan 

    - name: Terraform Apply
      run: terraform apply -auto-approve